import { Router, type IRouter } from "express";
import { uploadthingRouter } from "./uploadthing";
import healthRouter from "./health";
import usersRouter from "./users";
import clientsRouter from "./clients";
import tripsRouter from "./trips";
import reservationsRouter from "./reservations";
import paymentsRouter from "./payments";
import pipelineRouter from "./pipeline";
import communicationRouter from "./communication";
import registrationsRouter from "./registrations";
import marketingRouter from "./marketing";
import dashboardRouter from "./dashboard";
import loyaltyRouter from "./loyalty";
import commissionsRouter from "./commissions";
import referralsRouter from "./referrals";
import boardingRouter from "./boarding";
import couponsRouter from "./coupons";
import documentsRouter from "./documents";
import chatbotRouter from "./chatbot";
import auditRouter from "./audit";
import tenantsRouter from "./tenants";
import catalogRouter from "./catalog";
import automationExtrasRouter from "./automation-extras";
import systemConfigsRouter from "./system-configs";
import adminRouter from "./admin";
import plansRouter from "./plans";
import invoicesRouter from "./invoices";
import adminMetricsRouter from "./admin-metrics";
import platformSettingsRouter from "./platform-settings";
import storeRouter from "./store";
import storePublicRouter from "./store-public";
import onboardingRouter from "./onboarding";
import teamRouter from "./team";
import notificationsRouter from "./notifications";
import birthdayRouter from "./birthday";
import layoutsRouter from "./layouts";
import salesGoalsRouter from "./sales-goals";
import calendarRouter from "./calendar";
import tripCostsRouter from "./trip-costs";

const router: IRouter = Router();

router.use(adminRouter);
router.use(healthRouter);
router.use(dashboardRouter);
router.use(tenantsRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(tripsRouter);
router.use(reservationsRouter);
router.use(paymentsRouter);
router.use(pipelineRouter);
router.use(communicationRouter);
router.use(registrationsRouter);
router.use(marketingRouter);
router.use(loyaltyRouter);
router.use(commissionsRouter);
router.use(referralsRouter);
router.use(boardingRouter);
router.use(couponsRouter);
router.use(documentsRouter);
router.use(chatbotRouter);
router.use(auditRouter);
router.use(catalogRouter);
router.use(automationExtrasRouter);
router.use(systemConfigsRouter);
router.use(plansRouter);
router.use(invoicesRouter);
router.use(adminMetricsRouter);
router.use(platformSettingsRouter);
router.use(storeRouter);
router.use(storePublicRouter);
router.use(onboardingRouter);
router.use(teamRouter);
router.use(notificationsRouter);
router.use(birthdayRouter);
router.use(layoutsRouter);
router.use(salesGoalsRouter);
router.use(calendarRouter);
router.use(tripCostsRouter);
router.use("/uploadthing", uploadthingRouter);

export default router;
